# Eureka - disabled
eureka.client.enabled=false
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# JWT production
spring.security.oauth2.resource-server.jwt.issuer-uri=https://sso.isums.pro/realms/isums

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

# Keycloak
keycloak.base-url=https://sso.isums.pro

# gRPC - Service Connect DNS
spring.grpc.server.port=1012

spring.jpa.show-sql=false