name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  deploy:
    uses: Management-System-for-Rental-SEP490/.github/.github/workflows/deploy-java-service.yml@main
    with:
      service_name: user-service
      xmx: 640m
    secrets:
      EC2_HOST: ${{ secrets.EC2_HOST }}
      EC2_USER: ${{ secrets.EC2_USER }}
      EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
