name: Deploy

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  packages: write

jobs:
  deploy:
    uses: Management-System-for-Rental-SEP490/.github/.github/workflows/deploy-java-service.yml@main
    with:
      service_name: user-service
      xmx: 640m
    secrets:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
